# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, verbose_name='用户名')),
                ('upwd', models.CharField(max_length=30, verbose_name='密码')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
            ],
        ),
    ]
